#!/usr/bin/env python3
"""
tools/optimizer/core.py — Projected Gradient Descent Optimizer Core
====================================================================

This module implements the core optimization loop:
  1. Load parameter spec from YAML.
  2. Initialize at default point (or user-specified start).
  3. For each iteration:
     a. Compute gradient estimate (finite differences).
     b. Take a gradient step.
     c. PROJECT the candidate back into the box (before build/eval).
     d. Write build config, build kernel, boot in QEMU, parse [METRICS].
     e. Compute objective value.
     f. Log the evaluation point to append-only JSONL audit log.
  4. After N iterations or convergence, output best point + diff (A2 recommend mode).

The projection step (3c) is the safety-critical operation: it ensures no
out-of-bounds candidate can ever reach the build stage.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# Add repo root to path for imports
REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from tools.optimizer.projection import project_to_box
from tools.optimizer.spec import OptimizerSpec, ParameterSpec


@dataclass
class EvaluationPoint:
    """A single evaluated point in the optimization trace."""

    params: Dict[str, float]  # parameter name -> value
    objective: float
    raw_metrics: Dict[str, int]  # all [METRICS] key=value pairs
    image_hash: str  # SHA256 of the built kernel image
    timestamp: str  # ISO-8601 UTC
    iteration: int

    def to_jsonl(self) -> str:
        """Serialize to a JSONL line."""
        return json.dumps({
            "params": self.params,
            "objective": self.objective,
            "raw_metrics": self.raw_metrics,
            "image_hash": self.image_hash,
            "timestamp": self.timestamp,
            "iteration": self.iteration,
        }, sort_keys=True)

    @classmethod
    def from_jsonl(cls, line: str) -> "EvaluationPoint":
        """Deserialize from a JSONL line."""
        data = json.loads(line.strip())
        return cls(
            params=data["params"],
            objective=data["objective"],
            raw_metrics=data["raw_metrics"],
            image_hash=data["image_hash"],
            timestamp=data["timestamp"],
            iteration=data["iteration"],
        )


@dataclass
class OptimizationResult:
    """Final result of an optimization run."""

    best_params: Dict[str, float]
    best_objective: float
    total_iterations: int
    evaluations: List[EvaluationPoint]
    recommendation_diff: str  # unified diff of build-config change


class KernelBuilder:
    """Handles kernel build configuration and compilation."""

    def __init__(self, spec: OptimizerSpec):
        self.spec = spec
        self._config_template_path = REPO_ROOT / "src" / "kernel" / "config.h.template"
        self._config_path = REPO_ROOT / "src" / "kernel" / "config.h"

    def write_config(self, params: Dict[str, float]) -> None:
        """
        Write the build configuration file with the given parameter values.

        This maps each parameter's value to its build_key in the config.
        The config file is written atomically (write to temp, then rename).
        """
        lines = []
        lines.append("/* Auto-generated by tools/optimizer/core.py */")
        lines.append(f"/* Generated at: {datetime.now(timezone.utc).isoformat()} */")
        lines.append("")

        for p in self.spec.parameters:
            value = params.get(p.name, p.default)
            if p.param_type == "int":
                value = int(round(value))
                lines.append(f"#define {p.build_key} {value}")
            else:
                lines.append(f"#define {p.build_key} {value:.6f}")

        lines.append("")

        # Atomic write
        content = "\n".join(lines) + "\n"
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8", delete=False, suffix=".h"
        ) as tmp:
            tmp.write(content)
            tmp_path = tmp.name

        # Check for BOM (should not be present)
        with open(tmp_path, "rb") as f:
            first_bytes = f.read(3)
            if first_bytes.startswith(b"\xef\xbb\xbf"):
                raise ValueError("Generated config contains BOM")

        # Ensure parent directory exists
        self._config_path.parent.mkdir(parents=True, exist_ok=True)

        # Move to final location
        shutil.move(tmp_path, str(self._config_path))

    def build_kernel(self, output_iso_path: Path) -> str:
        """
        Build the kernel ISO image.

        Returns:
            SHA256 hash of the resulting ISO file.
        """
        # Run make to build the integration test ISO
        # Note: This assumes the repo has a Makefile with appropriate targets
        env = os.environ.copy()
        env["OPTIMIZER_BUILD"] = "1"

        result = subprocess.run(
            ["make", "integration-test-iso"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            env=env,
        )

        if result.returncode != 0:
            raise RuntimeError(f"Kernel build failed:\n{result.stderr}")

        # Find the built ISO
        iso_candidates = list(REPO_ROOT.glob("chimaera_*_test.iso"))
        if not iso_candidates:
            raise RuntimeError("Build succeeded but no ISO found")

        # Use the most recently modified ISO
        built_iso = max(iso_candidates, key=lambda p: p.stat().st_mtime)

        # Copy to requested output path
        shutil.copy2(str(built_iso), str(output_iso_path))

        # Compute SHA256
        sha256 = hashlib.sha256()
        with open(output_iso_path, "rb") as f:
            for chunk in iter(lambda: f.read(8192), b""):
                sha256.update(chunk)

        return sha256.hexdigest()


class MetricsParser:
    """Parses [METRICS] key=value lines from QEMU serial output."""

    METRICS_PATTERN = re.compile(r"^\[METRICS\]\s+(\w+)\s*=\s*(\S+)$")

    @classmethod
    def parse(cls, serial_lines: List[str]) -> Dict[str, int]:
        """
        Parse all [METRICS] key=value lines from serial output.

        Returns:
            Dictionary mapping metric names to integer values.
        """
        metrics = {}
        for line in serial_lines:
            match = cls.METRICS_PATTERN.match(line.strip())
            if match:
                key, value = match.groups()
                try:
                    metrics[key] = int(value)
                except ValueError:
                    # Skip non-integer metrics
                    pass
        return metrics


class Optimizer:
    """
    Projected gradient descent optimizer for ChimaeraOS parameters.

    Safety invariant: Every candidate point is projected into the constitutional
    box BEFORE being passed to write_config(), build_kernel(), or any evaluation.
    """

    def __init__(
        self,
        spec: OptimizerSpec,
        audit_log_path: Path,
        learning_rate: float = 0.1,
        max_iterations: int = 20,
        epsilon: float = 1e-4,  # Convergence threshold
    ):
        self.spec = spec
        self.audit_log_path = audit_log_path
        self.learning_rate = learning_rate
        self.max_iterations = max_iterations
        self.epsilon = epsilon

        self.builder = KernelBuilder(spec)
        self.evaluations: List[EvaluationPoint] = []

        # Ensure audit log directory exists
        self.audit_log_path.parent.mkdir(parents=True, exist_ok=True)

    def _compute_objective(self, metrics: Dict[str, int]) -> float:
        """
        Compute the scalar objective from raw metrics.

        For multi-parameter optimization, we aggregate across all parameters'
        metric_name fields. Each parameter specifies whether to minimize or
        maximize its associated metric.

        For simplicity in this initial implementation, we use a weighted sum
        where each parameter contributes equally. Parameters with "minimize"
        contribute positively; "maximize" contribute negatively.
        """
        total = 0.0
        for p in self.spec.parameters:
            metric_val = metrics.get(p.metric_name, 0)
            if p.objective == "minimize":
                total += metric_val
            else:  # maximize
                total -= metric_val
        return total

    def _estimate_gradient(
        self,
        current_params: Dict[str, float],
        current_objective: float,
    ) -> Dict[str, float]:
        """
        Estimate gradient using finite differences.

        For each parameter, perturb it slightly and measure the change in objective.
        This is a forward-difference approximation.
        """
        gradient = {}
        delta = 0.01  # Perturbation size

        for p in self.spec.parameters:
            perturbed = current_params.copy()
            perturbed[p.name] = current_params[p.name] + delta

            # Project the perturbed point (safety!)
            perturbed_values = [perturbed[name] for name in self.spec.param_names]
            lo_bounds = [param.lo for param in self.spec.parameters]
            hi_bounds = [param.hi for param in self.spec.parameters]
            projected_values, _ = project_to_box(perturbed_values, lo_bounds, hi_bounds)

            # Reconstruct perturbed dict with projected values
            for i, name in enumerate(self.spec.param_names):
                perturbed[name] = projected_values[i]

            # Evaluate perturbed point
            perturbed_obj = self._evaluate_point(perturbed, log_only=False)

            # Finite difference
            gradient[p.name] = (perturbed_obj - current_objective) / delta

        return gradient

    def _evaluate_point(
        self,
        params: Dict[str, float],
        iteration: int = 0,
        log_only: bool = False,
    ) -> float:
        """
        Evaluate a parameter point by building, booting, and measuring.

        Returns the objective value (lower is better for minimization).

        If log_only=True, skip the actual evaluation and return a placeholder
        (used during gradient estimation when we want to avoid full builds).
        """
        if log_only:
            # Placeholder for gradient estimation phase
            return 0.0

        timestamp = datetime.now(timezone.utc).isoformat()

        # Step 1: Write build config
        self.builder.write_config(params)

        # Step 2: Build kernel
        with tempfile.NamedTemporaryFile(suffix=".iso", delete=False) as tmp:
            iso_path = Path(tmp.name)

        try:
            image_hash = self.builder.build_kernel(iso_path)

            # Step 3: Boot in QEMU and capture serial
            from tests.integration.lib.qemu_runner import QEMURunner, DiskBuilder

            with tempfile.NamedTemporaryFile(suffix=".img", delete=False) as f:
                disk_path = f.name

            try:
                # Create disk with synthetic workload marker
                db = DiskBuilder(disk_path)
                db.write_file("SCENARIO", b"M")  # Metrics scenario

                runner = QEMURunner(
                    iso_path=str(iso_path),
                    disk_path=disk_path,
                    timeout=90,
                    done_markers=["[INTTEST] DONE", "[METRICS] DONE"],
                )

                exit_code = runner.run()
                serial_lines = runner.serial_log

            finally:
                try:
                    os.unlink(disk_path)
                except OSError:
                    pass

            # Step 4: Parse metrics
            raw_metrics = MetricsParser.parse(serial_lines)

            # Step 5: Compute objective
            objective = self._compute_objective(raw_metrics)

        finally:
            try:
                os.unlink(iso_path)
            except OSError:
                pass

        # Step 6: Log to audit trail (append-only JSONL)
        point = EvaluationPoint(
            params=params.copy(),
            objective=objective,
            raw_metrics=raw_metrics,
            image_hash=image_hash,
            timestamp=timestamp,
            iteration=iteration,
        )

        with open(self.audit_log_path, "a", encoding="utf-8") as f:
            f.write(point.to_jsonl() + "\n")

        self.evaluations.append(point)

        return objective

    def run(self, initial_params: Optional[Dict[str, float]] = None) -> OptimizationResult:
        """
        Run the projected gradient descent optimization loop.

        Args:
            initial_params: Starting point. If None, use defaults from spec.

        Returns:
            OptimizationResult with best point and recommendation diff.
        """
        # Initialize at default or user-specified point
        if initial_params is None:
            current_params = {p.name: p.default for p in self.spec.parameters}
        else:
            current_params = initial_params.copy()

        # Initial projection (safety: ensure starting point is feasible)
        param_values = [current_params[name] for name in self.spec.param_names]
        lo_bounds = [p.lo for p in self.spec.parameters]
        hi_bounds = [p.hi for p in self.spec.parameters]
        projected_values, _ = project_to_box(param_values, lo_bounds, hi_bounds)

        for i, name in enumerate(self.spec.param_names):
            current_params[name] = projected_values[i]

        # Evaluate initial point
        print(f"Iteration 0: initial params = {current_params}")
        current_objective = self._evaluate_point(current_params, iteration=0)
        print(f"  objective = {current_objective}")

        best_params = current_params.copy()
        best_objective = current_objective

        # Optimization loop
        for iteration in range(1, self.max_iterations + 1):
            print(f"\nIteration {iteration}:")

            # Estimate gradient
            gradient = self._estimate_gradient(current_params, current_objective)
            print(f"  gradient = {gradient}")

            # Take gradient step
            step_params = current_params.copy()
            for name in self.spec.param_names:
                if gradient[name] < 0:
                    # Negative gradient: increase parameter to reduce objective
                    step_params[name] += self.learning_rate
                else:
                    # Positive gradient: decrease parameter
                    step_params[name] -= self.learning_rate

            # PROJECT back into box (SAFETY CRITICAL)
            step_values = [step_params[name] for name in self.spec.param_names]
            projected_values, proj_distance = project_to_box(
                step_values, lo_bounds, hi_bounds
            )

            for i, name in enumerate(self.spec.param_names):
                step_params[name] = projected_values[i]

            print(f"  step (projected, dist={proj_distance:.4f}) = {step_params}")

            # Evaluate projected candidate
            new_objective = self._evaluate_point(step_params, iteration=iteration)
            print(f"  objective = {new_objective}")

            # Accept if improvement
            if new_objective < current_objective:
                print(f"  → accepted (improvement: {current_objective - new_objective:.4f})")
                current_params = step_params
                current_objective = new_objective

                if new_objective < best_objective:
                    best_params = step_params.copy()
                    best_objective = new_objective
            else:
                print(f"  → rejected (no improvement)")

            # Check convergence
            if proj_distance < self.epsilon:
                print(f"Converged: step distance {proj_distance} < epsilon {self.epsilon}")
                break

        # Generate recommendation diff
        recommendation_diff = self._generate_diff(best_params)

        return OptimizationResult(
            best_params=best_params,
            best_objective=best_objective,
            total_iterations=iteration,
            evaluations=self.evaluations.copy(),
            recommendation_diff=recommendation_diff,
        )

    def _generate_diff(self, best_params: Dict[str, float]) -> str:
        """
        Generate a unified diff showing the recommended build-config change.

        This compares the default config against the best-found config.
        """
        default_params = {p.name: p.default for p in self.spec.parameters}

        lines = []
        lines.append("--- config.h.default")
        lines.append("+++ config.h.optimized")
        lines.append("@@ Recommended parameter changes @@")

        for p in self.spec.parameters:
            default_val = default_params[p.name]
            best_val = best_params[p.name]

            if p.param_type == "int":
                default_str = str(int(round(default_val)))
                best_str = str(int(round(best_val)))
            else:
                default_str = f"{default_val:.6f}"
                best_str = f"{best_val:.6f}"

            if default_str != best_str:
                lines.append(f"-#define {p.build_key} {default_str}")
                lines.append(f"+#define {p.build_key} {best_str}")

        return "\n".join(lines) + "\n"
